server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: t0
    password: t0
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 10
      poolName: HikariPoolt0
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTimeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ejb:
          interceptor: com.cyber009.spring3.t0.common.interceptor.EntityAuditInterceptor

project:
  security:
    peppers:
      - ed85d7102073ac03dba4497351f0c4f3bceb729bf7b210ed4202290c227259a82b6b6dbb89c173077a4dc77865be8498
      - 1d85d7102073ac03dba4497351f0c4f3bceb729bf7b210ed4202290c227259a82b6b6dbb89c173077a4dc77865be8498

